/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AgenciesRouteImport } from './routes/agencies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReportScanIdRouteImport } from './routes/report/$scanId'
import { Route as PrintScanIdRouteImport } from './routes/print/$scanId'
import { Route as OnboardingStatusRouteImport } from './routes/onboarding/status'
import { Route as OnboardingClientIdRouteImport } from './routes/onboarding/$clientId'
import { Route as CheckoutTokenRouteImport } from './routes/checkout/$token'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as SitesClientIdFilenameRouteImport } from './routes/sites/$clientId/$filename'
import { Route as PrintClientClientIdRouteImport } from './routes/print/client/$clientId'
import { Route as OnboardingDnsSetupClientIdRouteImport } from './routes/onboarding/dns-setup/$clientId'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenciesRoute = AgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportScanIdRoute = ReportScanIdRouteImport.update({
  id: '/report/$scanId',
  path: '/report/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintScanIdRoute = PrintScanIdRouteImport.update({
  id: '/print/$scanId',
  path: '/print/$scanId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStatusRoute = OnboardingStatusRouteImport.update({
  id: '/onboarding/status',
  path: '/onboarding/status',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingClientIdRoute = OnboardingClientIdRouteImport.update({
  id: '/onboarding/$clientId',
  path: '/onboarding/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTokenRoute = CheckoutTokenRouteImport.update({
  id: '/checkout/$token',
  path: '/checkout/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesClientIdFilenameRoute = SitesClientIdFilenameRouteImport.update({
  id: '/sites/$clientId/$filename',
  path: '/sites/$clientId/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintClientClientIdRoute = PrintClientClientIdRouteImport.update({
  id: '/print/client/$clientId',
  path: '/print/client/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDnsSetupClientIdRoute =
  OnboardingDnsSetupClientIdRouteImport.update({
    id: '/onboarding/dns-setup/$clientId',
    path: '/onboarding/dns-setup/$clientId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/onboarding/$clientId': typeof OnboardingClientIdRoute
  '/onboarding/status': typeof OnboardingStatusRoute
  '/print/$scanId': typeof PrintScanIdRoute
  '/report/$scanId': typeof ReportScanIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/onboarding/dns-setup/$clientId': typeof OnboardingDnsSetupClientIdRoute
  '/print/client/$clientId': typeof PrintClientClientIdRoute
  '/sites/$clientId/$filename': typeof SitesClientIdFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/onboarding/$clientId': typeof OnboardingClientIdRoute
  '/onboarding/status': typeof OnboardingStatusRoute
  '/print/$scanId': typeof PrintScanIdRoute
  '/report/$scanId': typeof ReportScanIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/onboarding/dns-setup/$clientId': typeof OnboardingDnsSetupClientIdRoute
  '/print/client/$clientId': typeof PrintClientClientIdRoute
  '/sites/$clientId/$filename': typeof SitesClientIdFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agencies': typeof AgenciesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/onboarding/$clientId': typeof OnboardingClientIdRoute
  '/onboarding/status': typeof OnboardingStatusRoute
  '/print/$scanId': typeof PrintScanIdRoute
  '/report/$scanId': typeof ReportScanIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/onboarding/dns-setup/$clientId': typeof OnboardingDnsSetupClientIdRoute
  '/print/client/$clientId': typeof PrintClientClientIdRoute
  '/sites/$clientId/$filename': typeof SitesClientIdFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencies'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin/login'
    | '/checkout/$token'
    | '/onboarding/$clientId'
    | '/onboarding/status'
    | '/print/$scanId'
    | '/report/$scanId'
    | '/admin/'
    | '/api/webhooks/stripe'
    | '/onboarding/dns-setup/$clientId'
    | '/print/client/$clientId'
    | '/sites/$clientId/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agencies'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin/login'
    | '/checkout/$token'
    | '/onboarding/$clientId'
    | '/onboarding/status'
    | '/print/$scanId'
    | '/report/$scanId'
    | '/admin'
    | '/api/webhooks/stripe'
    | '/onboarding/dns-setup/$clientId'
    | '/print/client/$clientId'
    | '/sites/$clientId/$filename'
  id:
    | '__root__'
    | '/'
    | '/agencies'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/sitemap.xml'
    | '/admin/login'
    | '/checkout/$token'
    | '/onboarding/$clientId'
    | '/onboarding/status'
    | '/print/$scanId'
    | '/report/$scanId'
    | '/admin/'
    | '/api/webhooks/stripe'
    | '/onboarding/dns-setup/$clientId'
    | '/print/client/$clientId'
    | '/sites/$clientId/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenciesRoute: typeof AgenciesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CheckoutTokenRoute: typeof CheckoutTokenRoute
  OnboardingClientIdRoute: typeof OnboardingClientIdRoute
  OnboardingStatusRoute: typeof OnboardingStatusRoute
  PrintScanIdRoute: typeof PrintScanIdRoute
  ReportScanIdRoute: typeof ReportScanIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  OnboardingDnsSetupClientIdRoute: typeof OnboardingDnsSetupClientIdRoute
  PrintClientClientIdRoute: typeof PrintClientClientIdRoute
  SitesClientIdFilenameRoute: typeof SitesClientIdFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agencies': {
      id: '/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AgenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$scanId': {
      id: '/report/$scanId'
      path: '/report/$scanId'
      fullPath: '/report/$scanId'
      preLoaderRoute: typeof ReportScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$scanId': {
      id: '/print/$scanId'
      path: '/print/$scanId'
      fullPath: '/print/$scanId'
      preLoaderRoute: typeof PrintScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/status': {
      id: '/onboarding/status'
      path: '/onboarding/status'
      fullPath: '/onboarding/status'
      preLoaderRoute: typeof OnboardingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$clientId': {
      id: '/onboarding/$clientId'
      path: '/onboarding/$clientId'
      fullPath: '/onboarding/$clientId'
      preLoaderRoute: typeof OnboardingClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$token': {
      id: '/checkout/$token'
      path: '/checkout/$token'
      fullPath: '/checkout/$token'
      preLoaderRoute: typeof CheckoutTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$clientId/$filename': {
      id: '/sites/$clientId/$filename'
      path: '/sites/$clientId/$filename'
      fullPath: '/sites/$clientId/$filename'
      preLoaderRoute: typeof SitesClientIdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/client/$clientId': {
      id: '/print/client/$clientId'
      path: '/print/client/$clientId'
      fullPath: '/print/client/$clientId'
      preLoaderRoute: typeof PrintClientClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/dns-setup/$clientId': {
      id: '/onboarding/dns-setup/$clientId'
      path: '/onboarding/dns-setup/$clientId'
      fullPath: '/onboarding/dns-setup/$clientId'
      preLoaderRoute: typeof OnboardingDnsSetupClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenciesRoute: AgenciesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  CheckoutTokenRoute: CheckoutTokenRoute,
  OnboardingClientIdRoute: OnboardingClientIdRoute,
  OnboardingStatusRoute: OnboardingStatusRoute,
  PrintScanIdRoute: PrintScanIdRoute,
  ReportScanIdRoute: ReportScanIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  OnboardingDnsSetupClientIdRoute: OnboardingDnsSetupClientIdRoute,
  PrintClientClientIdRoute: PrintClientClientIdRoute,
  SitesClientIdFilenameRoute: SitesClientIdFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
